
build:
	equivs-build ns-control
	@echo TUTTO OK Riccardo

init:
	equivs-control ns-control

build-source:
	equivs-build --full ns-control

install:
	sudo dpkg -i *.deb

clean:
	rm palladius-ubuntu_*.deb